### ISSUE TITLE
create a Job class

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime2#23]
Job objects should be returned from ``SystemContext.__call__``, and should contain (at least) the complete job markdown, and the workflow uuid that gets stored as part of that jobs provenance. That workflow uuid can then be used, for example, in naming the markdown files that q2d3 is creating, which would provide a link from the ``Artifact`` objects that get created when the job is run to the actual code that was run, if the interface wants to track that (note that the created artifact's provenance does already have a reference to the workflow template that generated it).

**Comment by ebolyen** [comment]
:+1: It could also hold the expected filepaths of the completed artifacts.

**Comment by gregcaporaso** [comment]
+1

**Comment by wasade** [comment]
Parent or child relationships?

**Comment by ebolyen** [comment]
@wasade, not sure I understand your question. This would likely just be a simple struct-like object. If you are talking about workflows calling other workflows (and tracking it), the execution model isn't that sophisticated. We leave those decisions to super-systems (like Qiita).

**Comment by wasade** [comment]
Ah, okay. Just wondering if a job knew it's relationships. For instance, I
imagine a workflow might trigger a series of serial jobs, or a map/reduce
pattern.
