### ISSUE TITLE
artifact file extension?

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime2#6]
What should the recommended file extension be for serialized artifacts?

@gregcaporaso @ebolyen and I were thinking of `.qtf` for **Q**IIME **T**ar **F**ormat, since the format is a tar file. `.qtf` is only used by a couple of unrelated software packages and doesn't seem to be a popular extension.

The only thing I'm not sold on is having part of the underlying file format in the name (**T**ar) in case that changes in the future. It would also be nice to have "artifact" somewhere in the name since it is a format for serializing QIIME artifacts.

**Comment by ElDeveloper** [comment]
Some ideas:

* `.qink`: QIIME Is Not Kiime.
* `qing`: QIIME Is Not a Game.
* `qool`: QIIME O..... O..... L..... (fill in the blanks?).
* `foq` : Format Of QIIME.

**Comment by wasade** [comment]
Would it be possible to expand on the motivation to use a custom extension
as opposed to just .tar? I realize the nature of how things are packed in
the future might change, but on the other hand, reliance on standard
formats has an elegant simplicity to it

**Comment by ebolyen** [comment]
@wasade You bring up a good point. I think he motivation is to make these files generally opaque, but you can untar them if desired. It also makes finding artifacts easier as they have a particular extension. These aren't just any old tar files, they have a very specific meta-format to them that QIIME2 understands.

With respect to @jairideout's concern, I think if we changed from tar to zip, we would call those files something like `qzf` which would further distinguish them from any existing `qtf` files. It isn't much different from `.doc` vs `.docx`.

**Comment by ebolyen** [comment]
@ElDeveloper :-1: on `.qink` I would not be comfortable saying that out loud...

**Comment by wasade** [comment]
Okay, thanks, makes sense

**Comment by antgonza** [comment]
I like the idea of qzf (zip) or qtf (tar).

**Comment by gregcaporaso** [comment]
Sounds like we're in agreement on ``qzf`` and ``qtf``. Thanks!
