### ISSUE TITLE
should compressed artifacts be supported?

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime2#9]
Should there be an API for creating a compressed tar file with `Artifact.save`?

See [tarfile.open](https://docs.python.org/2/library/tarfile.html#tarfile.open) for supported compression schemes in Python. `Artifact.load` currently accepts compressed or uncompressed tar files, so supporting this should be trivial.

@ebolyen pointed out that a tar file is likely to be understood by software into the foreseeable future because it is a simple format, but compression is more of an unknown. IMO future-proof data archiving is outside the responsibility of QIIME 2, so we may want to give users/devs control over whether to compress artifacts. I could see different systems built around QIIME 2 having different needs w.r.t. compression.

**Comment by wasade** [comment]
One other option is to always use .tar, and if a format needs (or
supports?) compression, to compress that member specifically. This would
reduce operation time on the .tar file itself while still allowing for
minimizing space utilized for, say, demultiplexed sequence

**Comment by jairideout** [comment]
@wasade great idea, I think this is the way we should go!
